{
  "openapi": "3.0.0",
  "paths": {
    "/api/hello": {
      "get": {
        "operationId": "AppController_hello",
        "parameters": [
          {
            "name": "x-custom-lang",
            "in": "header",
            "description": "Custom language header",
            "required": false,
            "schema": { "default": "en", "example": "en", "type": "string" }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "app.hello" },
                    "statusCode": { "type": "number", "example": 200 },
                    "data": { "$ref": "#/components/schemas/AppHelloSerialization" }
                  }
                }
              }
            }
          },
          "408": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "http.serverError.requestTimeout" },
                    "statusCode": { "type": "number", "example": 5052 }
                  }
                }
              }
            }
          },
          "500": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "http.serverError.internalServerError" },
                    "statusCode": { "type": "number", "example": 5050 }
                  }
                }
              }
            }
          },
          "503": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "http.serverError.serviceUnavailable" },
                    "statusCode": { "type": "number", "example": 5051 }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/hello/api-key": {
      "get": {
        "operationId": "AppController_helloApiKey",
        "parameters": [
          {
            "name": "x-custom-lang",
            "in": "header",
            "description": "Custom language header",
            "required": false,
            "schema": { "default": "en", "example": "en", "type": "string" }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "app.helloApiKey" },
                    "statusCode": { "type": "number", "example": 200 },
                    "data": { "$ref": "#/components/schemas/AppHelloSerialization" }
                  }
                }
              }
            }
          },
          "401": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "oneOf": [
                    {
                      "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                      "properties": {
                        "message": { "example": "apiKey.error.keyNeeded" },
                        "statusCode": { "type": "number", "example": 5020 }
                      }
                    },
                    {
                      "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                      "properties": {
                        "message": { "example": "apiKey.error.notFound" },
                        "statusCode": { "type": "number", "example": 5021 }
                      }
                    },
                    {
                      "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                      "properties": {
                        "message": { "example": "apiKey.error.invalid" },
                        "statusCode": { "type": "number", "example": 5025 }
                      }
                    }
                  ]
                }
              }
            }
          },
          "408": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "http.serverError.requestTimeout" },
                    "statusCode": { "type": "number", "example": 5052 }
                  }
                }
              }
            }
          },
          "500": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "http.serverError.internalServerError" },
                    "statusCode": { "type": "number", "example": 5050 }
                  }
                }
              }
            }
          },
          "503": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "http.serverError.serviceUnavailable" },
                    "statusCode": { "type": "number", "example": 5051 }
                  }
                }
              }
            }
          }
        },
        "security": [{ "apiKey": [] }]
      }
    },
    "/api/public/message/languages": {
      "get": {
        "operationId": "MessagePublicController_languages",
        "parameters": [
          {
            "name": "x-custom-lang",
            "in": "header",
            "description": "Custom language header",
            "required": false,
            "schema": { "default": "en", "example": "en", "type": "string" }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "message.languages" },
                    "statusCode": { "type": "number", "example": 200 },
                    "data": { "$ref": "#/components/schemas/MessageLanguageSerialization" }
                  }
                }
              }
            }
          },
          "408": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "http.serverError.requestTimeout" },
                    "statusCode": { "type": "number", "example": 5052 }
                  }
                }
              }
            }
          },
          "500": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "http.serverError.internalServerError" },
                    "statusCode": { "type": "number", "example": 5050 }
                  }
                }
              }
            }
          },
          "503": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "http.serverError.serviceUnavailable" },
                    "statusCode": { "type": "number", "example": 5051 }
                  }
                }
              }
            }
          }
        },
        "tags": ["common.public.message"]
      }
    },
    "/api/v1/public/user/login": {
      "post": {
        "operationId": "UserPublicController_login",
        "parameters": [
          {
            "name": "x-custom-lang",
            "in": "header",
            "description": "Custom language header",
            "required": false,
            "schema": { "default": "en", "example": "en", "type": "string" }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": { "schema": { "$ref": "#/components/schemas/UserLoginDto" } }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "user.login" },
                    "statusCode": { "type": "number", "example": 200 },
                    "data": { "$ref": "#/components/schemas/UserLoginSerialization" }
                  }
                }
              }
            }
          },
          "408": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "http.serverError.requestTimeout" },
                    "statusCode": { "type": "number", "example": 5052 }
                  }
                }
              }
            }
          },
          "500": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "http.serverError.internalServerError" },
                    "statusCode": { "type": "number", "example": 5050 }
                  }
                }
              }
            }
          },
          "503": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "http.serverError.serviceUnavailable" },
                    "statusCode": { "type": "number", "example": 5051 }
                  }
                }
              }
            }
          }
        },
        "tags": ["modules.public.user"]
      }
    },
    "/api/v1/public/user/sign-up": {
      "post": {
        "operationId": "UserPublicController_signUp",
        "parameters": [
          {
            "name": "x-custom-lang",
            "in": "header",
            "description": "Custom language header",
            "required": false,
            "schema": { "default": "en", "example": "en", "type": "string" }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": { "schema": { "$ref": "#/components/schemas/UserSignUpDto" } }
          }
        },
        "responses": {
          "201": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "user.signup" },
                    "statusCode": { "type": "number", "example": 201 }
                  }
                }
              }
            }
          },
          "408": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "http.serverError.requestTimeout" },
                    "statusCode": { "type": "number", "example": 5052 }
                  }
                }
              }
            }
          },
          "500": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "http.serverError.internalServerError" },
                    "statusCode": { "type": "number", "example": 5050 }
                  }
                }
              }
            }
          },
          "503": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "http.serverError.serviceUnavailable" },
                    "statusCode": { "type": "number", "example": 5051 }
                  }
                }
              }
            }
          }
        },
        "tags": ["modules.public.user"]
      }
    },
    "/api/v1/admin/role/list": {
      "get": {
        "operationId": "RoleAdminController_list",
        "parameters": [
          {
            "name": "search",
            "required": false,
            "in": "query",
            "allowEmptyValue": true,
            "description": "Search will base on _availableSearch with rule contains, and case insensitive",
            "schema": { "type": "string" }
          },
          {
            "name": "perPage",
            "required": false,
            "in": "query",
            "allowEmptyValue": true,
            "example": 20,
            "description": "Data per page",
            "schema": { "type": "number" }
          },
          {
            "name": "page",
            "required": false,
            "in": "query",
            "allowEmptyValue": true,
            "example": 1,
            "description": "page number",
            "schema": { "type": "number" }
          },
          {
            "name": "orderBy",
            "required": false,
            "in": "query",
            "allowEmptyValue": true,
            "example": "createdAt",
            "description": "Order by base on _availableOrderBy",
            "schema": { "type": "string" }
          },
          {
            "name": "orderDirection",
            "required": false,
            "in": "query",
            "allowEmptyValue": true,
            "example": "asc",
            "description": "Order direction base on _availableOrderDirection",
            "schema": { "enum": ["asc", "desc"], "type": "string" }
          },
          {
            "name": "x-custom-lang",
            "in": "header",
            "description": "Custom language header",
            "required": false,
            "schema": { "default": "en", "example": "en", "type": "string" }
          },
          {
            "name": "isActive",
            "required": true,
            "in": "query",
            "allowEmptyValue": false,
            "example": "true,false",
            "description": "boolean value with ',' delimiter",
            "schema": { "type": "string" }
          },
          {
            "name": "type",
            "required": true,
            "in": "query",
            "allowEmptyValue": false,
            "example": "SUPER_ADMIN,USER,ADMIN",
            "description": "enum value with ',' delimiter",
            "schema": { "type": "string" }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponsePagingSerialization" }],
                  "properties": {
                    "message": { "example": "role.list" },
                    "statusCode": { "type": "number", "example": 200 },
                    "data": {
                      "type": "array",
                      "items": { "$ref": "#/components/schemas/RoleListSerialization" }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "oneOf": [
                    {
                      "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                      "properties": {
                        "message": { "example": "auth.error.accessTokenUnauthorized" },
                        "statusCode": { "type": "number", "example": 5000 }
                      }
                    },
                    {
                      "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                      "properties": {
                        "message": { "example": "apiKey.error.keyNeeded" },
                        "statusCode": { "type": "number", "example": 5020 }
                      }
                    },
                    {
                      "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                      "properties": {
                        "message": { "example": "apiKey.error.notFound" },
                        "statusCode": { "type": "number", "example": 5021 }
                      }
                    },
                    {
                      "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                      "properties": {
                        "message": { "example": "apiKey.error.invalid" },
                        "statusCode": { "type": "number", "example": 5025 }
                      }
                    }
                  ]
                }
              }
            }
          },
          "403": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "oneOf": [
                    {
                      "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                      "properties": {
                        "message": { "example": "role.error.typeForbidden" },
                        "statusCode": { "type": "number", "example": 5101 }
                      }
                    }
                  ]
                }
              }
            }
          },
          "408": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "http.serverError.requestTimeout" },
                    "statusCode": { "type": "number", "example": 5052 }
                  }
                }
              }
            }
          },
          "500": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "http.serverError.internalServerError" },
                    "statusCode": { "type": "number", "example": 5050 }
                  }
                }
              }
            }
          },
          "503": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "http.serverError.serviceUnavailable" },
                    "statusCode": { "type": "number", "example": 5051 }
                  }
                }
              }
            }
          }
        },
        "tags": ["common.admin.role"],
        "security": [{ "accessToken": [] }, { "apiKey": [] }]
      }
    },
    "/api/v1/admin/user/update/{user}/blocked": {
      "patch": {
        "operationId": "UserAdminController_blocked",
        "parameters": [
          {
            "name": "x-custom-lang",
            "in": "header",
            "description": "Custom language header",
            "required": false,
            "schema": { "default": "en", "example": "en", "type": "string" }
          },
          {
            "name": "user",
            "required": true,
            "in": "path",
            "allowEmptyValue": false,
            "example": "1f851b3a-b972-4e60-829e-a66a1244af5a",
            "schema": { "type": "string" }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "user.blocked" },
                    "statusCode": { "type": "number", "example": 200 }
                  }
                }
              }
            }
          },
          "401": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "oneOf": [
                    {
                      "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                      "properties": {
                        "message": { "example": "auth.error.accessTokenUnauthorized" },
                        "statusCode": { "type": "number", "example": 5000 }
                      }
                    },
                    {
                      "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                      "properties": {
                        "message": { "example": "apiKey.error.keyNeeded" },
                        "statusCode": { "type": "number", "example": 5020 }
                      }
                    },
                    {
                      "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                      "properties": {
                        "message": { "example": "apiKey.error.notFound" },
                        "statusCode": { "type": "number", "example": 5021 }
                      }
                    },
                    {
                      "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                      "properties": {
                        "message": { "example": "apiKey.error.invalid" },
                        "statusCode": { "type": "number", "example": 5025 }
                      }
                    }
                  ]
                }
              }
            }
          },
          "403": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "oneOf": [
                    {
                      "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                      "properties": {
                        "message": { "example": "role.error.typeForbidden" },
                        "statusCode": { "type": "number", "example": 5101 }
                      }
                    }
                  ]
                }
              }
            }
          },
          "408": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "http.serverError.requestTimeout" },
                    "statusCode": { "type": "number", "example": 5052 }
                  }
                }
              }
            }
          },
          "500": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "http.serverError.internalServerError" },
                    "statusCode": { "type": "number", "example": 5050 }
                  }
                }
              }
            }
          },
          "503": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "http.serverError.serviceUnavailable" },
                    "statusCode": { "type": "number", "example": 5051 }
                  }
                }
              }
            }
          }
        },
        "tags": ["modules.admin.user"],
        "security": [{ "accessToken": [] }, { "apiKey": [] }]
      }
    },
    "/api/v1/admin/user/update/{user}/active": {
      "patch": {
        "operationId": "UserAdminController_active",
        "parameters": [
          {
            "name": "x-custom-lang",
            "in": "header",
            "description": "Custom language header",
            "required": false,
            "schema": { "default": "en", "example": "en", "type": "string" }
          },
          {
            "name": "user",
            "required": true,
            "in": "path",
            "allowEmptyValue": false,
            "example": "1f851b3a-b972-4e60-829e-a66a1244af5a",
            "schema": { "type": "string" }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "user.blocked" },
                    "statusCode": { "type": "number", "example": 200 }
                  }
                }
              }
            }
          },
          "401": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "oneOf": [
                    {
                      "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                      "properties": {
                        "message": { "example": "auth.error.accessTokenUnauthorized" },
                        "statusCode": { "type": "number", "example": 5000 }
                      }
                    },
                    {
                      "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                      "properties": {
                        "message": { "example": "apiKey.error.keyNeeded" },
                        "statusCode": { "type": "number", "example": 5020 }
                      }
                    },
                    {
                      "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                      "properties": {
                        "message": { "example": "apiKey.error.notFound" },
                        "statusCode": { "type": "number", "example": 5021 }
                      }
                    },
                    {
                      "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                      "properties": {
                        "message": { "example": "apiKey.error.invalid" },
                        "statusCode": { "type": "number", "example": 5025 }
                      }
                    }
                  ]
                }
              }
            }
          },
          "403": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "oneOf": [
                    {
                      "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                      "properties": {
                        "message": { "example": "role.error.typeForbidden" },
                        "statusCode": { "type": "number", "example": 5101 }
                      }
                    }
                  ]
                }
              }
            }
          },
          "408": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "http.serverError.requestTimeout" },
                    "statusCode": { "type": "number", "example": 5052 }
                  }
                }
              }
            }
          },
          "500": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "http.serverError.internalServerError" },
                    "statusCode": { "type": "number", "example": 5050 }
                  }
                }
              }
            }
          },
          "503": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "http.serverError.serviceUnavailable" },
                    "statusCode": { "type": "number", "example": 5051 }
                  }
                }
              }
            }
          }
        },
        "tags": ["modules.admin.user"],
        "security": [{ "accessToken": [] }, { "apiKey": [] }]
      }
    },
    "/api/v1/admin/user/update/{user}/inactive": {
      "patch": {
        "operationId": "UserAdminController_inactive",
        "parameters": [
          {
            "name": "x-custom-lang",
            "in": "header",
            "description": "Custom language header",
            "required": false,
            "schema": { "default": "en", "example": "en", "type": "string" }
          },
          {
            "name": "user",
            "required": true,
            "in": "path",
            "allowEmptyValue": false,
            "example": "1f851b3a-b972-4e60-829e-a66a1244af5a",
            "schema": { "type": "string" }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "user.blocked" },
                    "statusCode": { "type": "number", "example": 200 }
                  }
                }
              }
            }
          },
          "401": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "oneOf": [
                    {
                      "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                      "properties": {
                        "message": { "example": "auth.error.accessTokenUnauthorized" },
                        "statusCode": { "type": "number", "example": 5000 }
                      }
                    },
                    {
                      "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                      "properties": {
                        "message": { "example": "apiKey.error.keyNeeded" },
                        "statusCode": { "type": "number", "example": 5020 }
                      }
                    },
                    {
                      "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                      "properties": {
                        "message": { "example": "apiKey.error.notFound" },
                        "statusCode": { "type": "number", "example": 5021 }
                      }
                    },
                    {
                      "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                      "properties": {
                        "message": { "example": "apiKey.error.invalid" },
                        "statusCode": { "type": "number", "example": 5025 }
                      }
                    }
                  ]
                }
              }
            }
          },
          "403": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "oneOf": [
                    {
                      "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                      "properties": {
                        "message": { "example": "role.error.typeForbidden" },
                        "statusCode": { "type": "number", "example": 5101 }
                      }
                    }
                  ]
                }
              }
            }
          },
          "408": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "http.serverError.requestTimeout" },
                    "statusCode": { "type": "number", "example": 5052 }
                  }
                }
              }
            }
          },
          "500": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "http.serverError.internalServerError" },
                    "statusCode": { "type": "number", "example": 5050 }
                  }
                }
              }
            }
          },
          "503": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "http.serverError.serviceUnavailable" },
                    "statusCode": { "type": "number", "example": 5051 }
                  }
                }
              }
            }
          }
        },
        "tags": ["modules.admin.user"],
        "security": [{ "accessToken": [] }, { "apiKey": [] }]
      }
    },
    "/api/v1/auth/user/refresh": {
      "post": {
        "operationId": "UserAuthController_refresh",
        "parameters": [
          {
            "name": "x-custom-lang",
            "in": "header",
            "description": "Custom language header",
            "required": false,
            "schema": { "default": "en", "example": "en", "type": "string" }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "user.refresh" },
                    "statusCode": { "type": "number", "example": 200 },
                    "data": { "$ref": "#/components/schemas/UserLoginSerialization" }
                  }
                }
              }
            }
          },
          "401": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "oneOf": [
                    {
                      "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                      "properties": {
                        "message": { "example": "auth.error.refreshTokenUnauthorized" },
                        "statusCode": { "type": "number", "example": 5001 }
                      }
                    },
                    {
                      "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                      "properties": {
                        "message": { "example": "apiKey.error.keyNeeded" },
                        "statusCode": { "type": "number", "example": 5020 }
                      }
                    },
                    {
                      "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                      "properties": {
                        "message": { "example": "apiKey.error.notFound" },
                        "statusCode": { "type": "number", "example": 5021 }
                      }
                    },
                    {
                      "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                      "properties": {
                        "message": { "example": "apiKey.error.invalid" },
                        "statusCode": { "type": "number", "example": 5025 }
                      }
                    }
                  ]
                }
              }
            }
          },
          "408": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "http.serverError.requestTimeout" },
                    "statusCode": { "type": "number", "example": 5052 }
                  }
                }
              }
            }
          },
          "500": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "http.serverError.internalServerError" },
                    "statusCode": { "type": "number", "example": 5050 }
                  }
                }
              }
            }
          },
          "503": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [{ "$ref": "#/components/schemas/ResponseDefaultSerialization" }],
                  "properties": {
                    "message": { "example": "http.serverError.serviceUnavailable" },
                    "statusCode": { "type": "number", "example": 5051 }
                  }
                }
              }
            }
          }
        },
        "tags": ["modules.auth.user"],
        "security": [{ "refreshToken": [] }, { "apiKey": [] }]
      }
    }
  },
  "info": {
    "title": "SpecFinderAPI APIs Specification",
    "description": "Section for describe whole APIs",
    "version": "1.0",
    "contact": {}
  },
  "tags": [{ "name": "API's", "description": "" }],
  "servers": [{ "url": "/" }, { "url": "/staging" }, { "url": "/prod" }],
  "components": {
    "securitySchemes": {
      "accessToken": { "scheme": "bearer", "bearerFormat": "JWT", "type": "http" },
      "refreshToken": { "scheme": "bearer", "bearerFormat": "JWT", "type": "http" },
      "apiKey": { "type": "apiKey", "in": "header", "name": "x-api-key" }
    },
    "schemas": {
      "ResponseDefaultSerialization": {
        "type": "object",
        "properties": {
          "statusCode": {
            "type": "number",
            "nullable": false,
            "description": "return specific status code for every endpoints",
            "example": 200
          },
          "message": {
            "nullable": false,
            "description": "Message base on language",
            "oneOf": [
              { "type": "string", "example": "message endpoint" },
              { "type": "object", "example": { "en": "This is test endpoint." } }
            ]
          },
          "_metadata": {
            "type": "object",
            "nullable": true,
            "description": "Contain metadata about API",
            "example": {
              "languages": ["en"],
              "timestamp": 1660190937231,
              "timezone": "Asia/Jakarta",
              "requestId": "40c2f734-7247-472b-bc26-8eff6e669781",
              "path": "/api/v1/test/hello",
              "version": "1",
              "repoVersion": "1.0.0"
            }
          }
        },
        "required": ["statusCode", "message", "_metadata"]
      },
      "AppHelloSerialization": {
        "type": "object",
        "properties": {
          "userAgent": {
            "type": "object",
            "example": {
              "ua": "PostmanRuntime/7.29.0",
              "browser": {},
              "engine": {},
              "os": {},
              "device": {},
              "cpu": {}
            }
          },
          "date": {
            "format": "date-time",
            "type": "string",
            "example": "2023-06-25T09:17:17.579Z"
          },
          "format": { "type": "string", "example": "2023-06-25T18:26:01.375Z" },
          "timestamp": { "type": "number", "example": 1660190937231 }
        },
        "required": ["userAgent", "date", "format", "timestamp"]
      },
      "MessageLanguageSerialization": {
        "type": "object",
        "properties": {
          "language": { "type": "array", "items": { "type": "string", "enum": ["en", "th"] } }
        },
        "required": ["language"]
      },
      "UserLoginSerialization": {
        "type": "object",
        "properties": {
          "tokenType": { "type": "string", "example": "Bearer" },
          "expiresIn": {
            "type": "string",
            "example": 1660190937231,
            "description": "Expire in timestamp"
          },
          "accessToken": {
            "type": "string",
            "example": "upr0tOFSJTJtjpVfVRjiV4rYbOT4PK",
            "description": "Will be valid JWT Encode string"
          },
          "refreshToken": {
            "type": "string",
            "example": "sUNxrnXl9RUhYsjXklll7sFAsEKRpA",
            "description": "Will be valid JWT Encode string"
          }
        },
        "required": ["tokenType", "expiresIn", "accessToken", "refreshToken"]
      },
      "UserLoginDto": {
        "type": "object",
        "properties": {
          "email": { "type": "string", "example": "Ines_Reilly67@gmail.com" },
          "password": {
            "type": "string",
            "description": "string password",
            "example": "qgz2lVAHXT@@!123"
          }
        },
        "required": ["email", "password"]
      },
      "UserSignUpDto": {
        "type": "object",
        "properties": {
          "email": { "type": "string", "example": "Ines_Reilly67@gmail.com" },
          "firstName": { "type": "string", "example": "Henry" },
          "userName": { "type": "string", "example": "Leslie" },
          "lastName": { "type": "string", "example": "Carter" },
          "mobileNumber": { "type": "string", "example": "62812813434004" },
          "password": {
            "type": "string",
            "description": "string password",
            "example": "qgz2lVAHXT@@!123"
          }
        },
        "required": ["email", "firstName", "lastName", "mobileNumber", "password"]
      },
      "ResponsePagingSerialization": {
        "type": "object",
        "properties": {
          "statusCode": {
            "type": "number",
            "nullable": false,
            "description": "return specific status code for every endpoints",
            "example": 200
          },
          "message": {
            "nullable": false,
            "description": "Message base on language",
            "oneOf": [
              { "type": "string", "example": "message endpoint" },
              { "type": "object", "example": { "en": "This is test endpoint." } }
            ]
          },
          "_metadata": {
            "type": "object",
            "nullable": false,
            "description": "Contain metadata about API",
            "example": {
              "languages": ["en"],
              "timestamp": 1660190937231,
              "timezone": "Asia/Jakarta",
              "requestId": "40c2f734-7247-472b-bc26-8eff6e669781",
              "path": "/api/v1/test/hello",
              "version": "1",
              "repoVersion": "1.0.0",
              "pagination": {
                "search": "Vladimir",
                "page": 1,
                "perPage": 20,
                "orderBy": "createdAt",
                "orderDirection": "asc",
                "availableSearch": ["name"],
                "availableOrderBy": ["createdAt"],
                "availableOrderDirection": ["asc", "desc"],
                "total": 100,
                "totalPage": 5
              },
              "cursor": {
                "nextPage": "http://217.0.0.1/__path?perPage=10&page=3&search=abc",
                "previousPage": "http://217.0.0.1/__path?perPage=10&page=1&search=abc",
                "firstPage": "http://217.0.0.1/__path?perPage=10&page=1&search=abc",
                "lastPage": "http://217.0.0.1/__path?perPage=10&page=20&search=abc"
              }
            }
          }
        },
        "required": ["statusCode", "message", "_metadata"]
      },
      "RoleListSerialization": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string",
            "description": "Id that representative with your target data",
            "example": "631d9f32a65cf07250b8938c"
          },
          "name": {
            "type": "string",
            "description": "Name of role",
            "example": "Senior Solutions Associate"
          },
          "description": {
            "type": "string",
            "description": "Description of role",
            "example": "Numquam dolore vero quidem sint in consequatur porro.",
            "nullable": true
          },
          "isActive": { "type": "boolean", "description": "Active flag of role", "example": true },
          "type": {
            "type": "string",
            "description": "Representative for role type",
            "example": "ADMIN"
          },
          "createdAt": {
            "format": "date-time",
            "type": "string",
            "description": "Date created at",
            "example": "2023-06-26T07:34:34.330Z"
          },
          "updatedAt": {
            "format": "date-time",
            "type": "string",
            "description": "Date updated at",
            "example": "2023-06-25T21:39:42.857Z"
          },
          "permissions": { "type": "number", "description": "count of permissions" }
        },
        "required": ["_id", "name", "isActive", "type", "createdAt", "permissions"]
      }
    }
  }
}
